services:

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: etimoshin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - spring

  eureka-server:
    image: etimoshin/eureka-server:latest
    container_name: eureka-server
    ports:
      - 8761:8761
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin

  apigw:
    image: etimoshin/apigw:latest
    container_name: apigw
    ports:
      - 8084:8084
    networks:
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - zipkin
      - eureka-server

  customer:
    image: etimoshin/customer:latest
    container_name: customer
    ports:
      - 8080:8080
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - zipkin
      - rabbitmq
      - eureka-server

  fraud:
    image: etimoshin/fraud:latest
    container_name: fraud
    ports:
      - 8081:8081
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - zipkin
      - eureka-server
      - rabbitmq

  notification:
    image: etimoshin/notification:latest
    container_name: notification
    ports:
      - 8083:8083
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
      - zipkin
      - rabbitmq
      - eureka-server

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: