server:
  port: 8083

spring:
  application:
    name: notification
  datasource:
    username: etimoshin
    password: password
    url: jdbc:postgresql://localhost:5432/notification
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show_sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false


rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    queue-name: notification
  routing-key:
    key: routing-key